# Generated by Django 2.2.1 on 2019-06-06 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_empleado', models.IntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('f_nac', models.DateField(blank=True, max_length=200, null=True)),
                ('d_pendientes', models.IntegerField(blank=True, null=True)),
                ('h_pendientes', models.FloatField(blank=True, null=True)),
                ('f_init', models.DateField(blank=True, max_length=200, null=True)),
                ('init_vac', models.DateField(blank=True, max_length=200, null=True)),
                ('fin_vac', models.DateField(blank=True, max_length=200, null=True)),
                ('ul_vac_tomadas', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('disponed_id', models.AutoField(primary_key=True, serialize=False)),
                ('disponsicion', models.CharField(choices=[('Disponer', 'Disponer'), ('Vacaciones', 'Vacaciones')], max_length=255, null=True)),
                ('fec', models.DateTimeField(auto_now=True)),
                ('razon_2', models.TextField(blank=True, max_length=255, null=True)),
                ('periodo_i', models.DateField(max_length=200, null=True)),
                ('periodo_f', models.DateField(max_length=200, null=True)),
                ('dias_disponer', models.IntegerField(null=True)),
                ('horas_disponer', models.FloatField(null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('solicitudes_id', models.AutoField(primary_key=True, serialize=False)),
                ('petit', models.CharField(choices=[('Adicionar', 'Adicionar')], max_length=255, null=True)),
                ('fec', models.DateTimeField(auto_now=True)),
                ('razon', models.TextField(blank=True, max_length=255, null=True)),
                ('periodo_init', models.DateField(blank=True, max_length=200, null=True)),
                ('periodo_fin', models.DateField(blank=True, max_length=200, null=True)),
                ('dias_adicion', models.IntegerField(null=True)),
                ('horas_adicion', models.FloatField(null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.CharField(blank=True, choices=[('Aprobar', 'Aprobar'), ('Declinar', 'Declinar')], max_length=255, null=True)),
                ('fecha_act', models.DateTimeField(auto_now=True)),
                ('disponed_id', models.ManyToManyField(to='devlocl.Disponibilidad')),
                ('solicitudes_id', models.ManyToManyField(to='devlocl.Peticion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
