# Generated by Django 2.2.1 on 2019-06-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlocl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='localusers',
            name='usuario',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
