# Generated by Django 2.2.1 on 2019-06-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlocl', '0002_auto_20190604_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='localusers',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localusers',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
